// ═══════════════════════════════════════════════════════════
// Beautiful PDF Generator
// 2 Pages: Charts + Calculation Table
// ═══════════════════════════════════════════════════════════

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { TitrationResult, ExperimentConfig, ChartConfig } from '@/types';

// ─── Colors ───
const PURPLE: [number, number, number] = [108, 99, 255];
const DARK_TEXT: [number, number, number] = [33, 33, 33];
const GRAY_TEXT: [number, number, number] = [120, 120, 120];
const YELLOW_BG: [number, number, number] = [255, 249, 196];
const ZEBRA_GRAY: [number, number, number] = [245, 245, 245];
const WHITE: [number, number, number] = [255, 255, 255];

// ─── Page Settings ───
const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 15;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const TOTAL_PAGES = 2;

// ─── Draw Header Bar ───
function drawHeader(pdf: jsPDF, pageNum: number) {
    // Header bar สีม่วง
    pdf.setFillColor(...PURPLE);
    pdf.rect(0, 0, PAGE_WIDTH, 18, 'F');

    // Logo text
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Titration Graph Generator', MARGIN, 12);

    // Page number
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Page ${pageNum}/${TOTAL_PAGES}`, PAGE_WIDTH - MARGIN, 12, {
        align: 'right',
    });
}

// ─── Draw Footer ───
function drawFooter(pdf: jsPDF) {
    pdf.setDrawColor(200, 200, 200);
    pdf.line(MARGIN, PAGE_HEIGHT - 15, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 15);

    pdf.setTextColor(...GRAY_TEXT);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'italic');
    pdf.text('Generated by Titration Graph Generator', MARGIN, PAGE_HEIGHT - 10);

    // วันเวลาที่สร้าง
    const now = new Date().toLocaleString('th-TH');
    pdf.text(now, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 10, { align: 'right' });
}

// ─── Draw Rounded Box ───
function drawRoundedBox(
    pdf: jsPDF,
    x: number,
    y: number,
    w: number,
    h: number,
    options?: { fill?: boolean; shadow?: boolean }
) {
    if (options?.shadow) {
        pdf.setFillColor(230, 230, 230);
        pdf.roundedRect(x + 1, y + 1, w, h, 3, 3, 'F');
    }
    pdf.setDrawColor(200, 200, 200);
    pdf.setFillColor(255, 255, 255);
    pdf.roundedRect(x, y, w, h, 3, 3, options?.fill ? 'FD' : 'D');
}

// ─── Main Export Function ───
export async function exportPDF(
    result: TitrationResult,
    config: ExperimentConfig,
    chartConfig: ChartConfig,
    profile: { full_name: string; university: string },
    phChartCanvas: HTMLCanvasElement,
    dvChartCanvas: HTMLCanvasElement
): Promise<void> {
    const pdf = new jsPDF('p', 'mm', 'a4');

    // ═══════════════════════════════
    // PAGE 1
    // ═══════════════════════════════
    drawHeader(pdf, 1);
    let y = 25;

    // ── ข้อมูลการทดลอง (กรอบมุมมน) ──
    drawRoundedBox(pdf, MARGIN, y, CONTENT_WIDTH, 42, {
        fill: true,
        shadow: true,
    });

    pdf.setTextColor(...PURPLE);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Experiment Information', MARGIN + 5, y + 8);

    pdf.setTextColor(...DARK_TEXT);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');

    const infoX = MARGIN + 8;
    const infoValX = MARGIN + 45;
    let infoY = y + 16;

    const info = [
        ['Experiment', `${config.expName} ${config.expNo}`],
        ['Experimenter', config.studentName || '-'],
        ['University', profile.university || '-'],
        [
            'Date',
            new Date().toLocaleDateString('th-TH', {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
            }),
        ],
    ];

    for (const [label, value] of info) {
        pdf.setFont('helvetica', 'bold');
        pdf.text(`${label}:`, infoX, infoY);
        pdf.setFont('helvetica', 'normal');
        pdf.text(value, infoValX, infoY);
        infoY += 6;
    }

    y += 48;

    // ── กราฟ 1: pH vs Volume ──
    pdf.setTextColor(...DARK_TEXT);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Graph 1: pH vs ${config.xLabel}`, MARGIN, y);
    y += 4;

    // กรอบกราฟ (มุมมน + เงา)
    const graphHeight = 85;
    drawRoundedBox(pdf, MARGIN, y, CONTENT_WIDTH, graphHeight, { shadow: true });

    // ใส่กราฟ
    const phImage = phChartCanvas.toDataURL('image/png', 1.0);
    pdf.addImage(
        phImage,
        'PNG',
        MARGIN + 2,
        y + 2,
        CONTENT_WIDTH - 4,
        graphHeight - 4
    );
    y += graphHeight + 6;

    // ── กราฟ 2: ΔpH/ΔV vs Volume ──
    pdf.setTextColor(...DARK_TEXT);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Graph 2: dpH/dV vs ${config.xLabel}`, MARGIN, y);
    y += 4;

    drawRoundedBox(pdf, MARGIN, y, CONTENT_WIDTH, graphHeight, { shadow: true });

    const dvImage = dvChartCanvas.toDataURL('image/png', 1.0);
    pdf.addImage(
        dvImage,
        'PNG',
        MARGIN + 2,
        y + 2,
        CONTENT_WIDTH - 4,
        graphHeight - 4
    );

    drawFooter(pdf);

    // ═══════════════════════════════
    // PAGE 2
    // ═══════════════════════════════
    pdf.addPage();
    drawHeader(pdf, 2);
    y = 25;

    // ── ตาราง ──
    pdf.setTextColor(...DARK_TEXT);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Calculation Results', MARGIN, y);
    y += 4;

    // สร้างข้อมูลตาราง
    const tableBody: (string | number)[][] = [];

    // แถวแรก (ไม่มี ΔpH, ΔV, ΔpH/ΔV)
    tableBody.push([
        result.volume[0].toFixed(2),
        result.pH[0].toFixed(2),
        '—',
        '—',
        '—',
    ]);

    // แถวที่เหลือ
    for (let i = 0; i < result.dPHdV.length; i++) {
        tableBody.push([
            result.volume[i + 1].toFixed(2),
            result.pH[i + 1].toFixed(2),
            result.deltaPH[i].toFixed(2),
            result.deltaV[i].toFixed(2),
            result.dPHdV[i].toFixed(2),
        ]);
    }

    autoTable(pdf, {
        startY: y,
        head: [['Volume (mL)', 'pH', 'ΔpH', 'ΔV', 'ΔpH/ΔV']],
        body: tableBody,
        theme: 'grid',
        headStyles: {
            fillColor: PURPLE,
            textColor: [255, 255, 255],
            fontStyle: 'bold',
            halign: 'center',
            fontSize: 10,
        },
        bodyStyles: {
            halign: 'center',
            fontSize: 9,
            textColor: DARK_TEXT,
        },
        alternateRowStyles: {
            fillColor: ZEBRA_GRAY,
        },
        // Highlight End Point row
        didParseCell: (data) => {
            // eqIndex + 1 because first row is "—" row
            if (data.section === 'body' && data.row.index === result.eqIndex + 1) {
                data.cell.styles.fillColor = YELLOW_BG;
                data.cell.styles.fontStyle = 'bold';
                data.cell.styles.textColor = [180, 130, 0];
            }
        },
        margin: { left: MARGIN, right: MARGIN },
    });

    y = (pdf as any).lastAutoTable.finalY + 8;

    // ── สรุปผล (กรอบมุมมน) ──
    const summaryHeight = 55;
    drawRoundedBox(pdf, MARGIN, y, CONTENT_WIDTH, summaryHeight, {
        fill: true,
        shadow: true,
    });

    pdf.setTextColor(...PURPLE);
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Summary', MARGIN + 5, y + 8);

    pdf.setTextColor(...DARK_TEXT);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');

    const sumX = MARGIN + 8;
    let sumY = y + 16;

    const summaryLines = [
        `End Point (pH Graph):  Volume = ${result.eqVol.toFixed(2)} mL,  pH = ${result.eqPH.toFixed(2)}`,
        `End Point (dpH/dV Graph):  Volume = ${result.eqVol.toFixed(2)} mL,  dpH/dV = ${result.eqDPHdV.toFixed(2)}`,
        '',
        `Type: ${result.expType}`,
        `Data Points: ${result.volume.length}    Volume Range: ${result.volume[0].toFixed(2)} - ${result.volume[result.volume.length - 1].toFixed(2)} mL`,
        `pH Range: ${Math.min(...result.pH).toFixed(2)} - ${Math.max(...result.pH).toFixed(2)}`,
    ];

    for (const line of summaryLines) {
        if (line.startsWith('Type')) {
            pdf.setFont('helvetica', 'bold');
        } else {
            pdf.setFont('helvetica', 'normal');
        }
        pdf.text(line, sumX, sumY);
        sumY += 5;
    }

    y += summaryHeight + 15;

    // ── ลงชื่อ ──
    pdf.setTextColor(...DARK_TEXT);
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');

    const signX = PAGE_WIDTH - MARGIN - 60;
    pdf.text('Signature ________________________', signX, y);
    y += 6;
    pdf.text(`(${config.studentName || '________________'})`, signX + 15, y);

    drawFooter(pdf);

    // ═══ Save ═══
    const fileName = `${config.expName}_${config.expNo}_report.pdf`.replace(
        /\s+/g,
        '_'
    );
    pdf.save(fileName);
}
